borrowbro/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/urls.py
from django.urls import path
from . import views

urlpatterns =[
	path('', views.index, name='index'),
	path('items/', views.ItemListView.as_view(), name='items'),
	path('item/<int:pk>', views.ItemDetailView.as_view(), name='item-detail'),
	path('owners/', views.OwnerListView.as_view(), name='owners'),
	path('owner/<int:pk>', views.OwnerDetailView.as_view(), name='owner-detail'),
	path('myitems/', views.LoanedItemsListView.as_view(), name='my-borrowed'),
]

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid #for unique instances
from django.contrib.auth.models import User
from datetime import date

# Create your models here.
class Category(models.Model):
	name = models.CharField(max_length=100, help_text="Input category (e.g. Home, Office)")

	def __str__(self):
		return self.name

class Item(models.Model):
	name = models.CharField(max_length=100)
	owner = models.ForeignKey('Owner', on_delete=models.SET_NULL, null=True) #1 item = 1 owner, 1 owner = many items
	summary = models.TextField(max_length=1000, help_text='Input description of the item')
	category = models.ManyToManyField(Category)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('item-detail', args=[str(self.id)])

	def get_category(self):
		return ', '.join([category.name for category in self.category.all()[:3]])
	get_category.short_description = 'Category'

class Owner(models.Model):
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)
	date_of_birth = models.DateField(null=True, blank=True)
	location = models.CharField(max_length=50)

	class Meta:
		ordering = ["last_name","first_name"]

	def get_absolute_url(self):
		return reverse('owner-detail', args=[str(self.id)])

	def __str__(self):
		return '{0}, {1}'.format(self.last_name, self.first_name)

class ItemInstance(models.Model):
	id = models.UUIDField(primary_key=True, default=uuid.uuid4)
	item = models.ForeignKey('Item', on_delete=models.SET_NULL, null=True) 
	due_back = models.DateField(null=True, blank=True)
	loan_status = (('o', 'On loan'),('a', 'Available'),('r', 'Reserved'))
	status = models.CharField(max_length=1, choices=loan_status, blank=True, default='a')
	borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
	
	class Meta:
		ordering = ["due_back"]
		permissions = (("can_mark_returned", "Set item as returned"),)

	def __str__(self):
		return '{0} ({1})'.format(self.id,self.item.name)

	@property #gets property
	def is_overdue(self):
		if self.due_back and date.today() > self.due_back:
			return True
		return False

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime

class RenewItem (forms.Form):
	renewal_date = forms.DateField()

catalog/views.py
from django.shortcuts import render
from .models import Item, ItemInstance, Owner, Category
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin #pearl needed
# Create your views here.

def index(request):
	num_items = Item.objects.all().count()
	num_instances = ItemInstance.objects.all().count()

	num_instances_available = ItemInstance.objects.filter(status__exact='a').count()
	num_owners = Owner.objects.count()

	num_visits = request.session.get('num_visits', 0)
	request.session['num_visits'] = num_visits+1

	return render(
		request,
		'index.html',
		context = {'num_items':num_items, 'num_instances':num_instances, 'num_instances_available':num_instances_available,
		'num_owners':num_owners, 'num_visits':num_visits},
	)

class ItemListView(generic.ListView):
	model = Item

	def get_context_data(self, **kwargs):
		context = super(ItemListView, self).get_context_data(**kwargs)
		return context

class ItemDetailView(generic.DetailView):
	model = Item

class OwnerListView(generic.ListView):
	model = Owner

	def get_context_data(self, **kwargs):
		context = super(OwnerListView, self).get_context_data(**kwargs)
		return context

class OwnerDetailView(generic.DetailView):
	model = Owner

class LoanedItemsListView(LoginRequiredMixin,generic.ListView):
	model = ItemInstance
	template_name ='catalog/iteminstance_list_borrowed.html'

	def get_queryset(self):
		return ItemInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% block title %}<title>Borrow Bro</title>{% endblock %}
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway" />
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Playfair+Display" />
	<link rel="icon" href="http://icons.iconarchive.com/icons/iconka/easter-egg-bunny/256/red-cute-icon.png">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
	<div class = "container-fluid">
		<div class='row'>
			<div class = "col-sm-2">
				{% block sidebar %}
				<ul class = "sidebar-nav">
					<li><a href="{% url 'index' %}">Home</a></li>
					<li><a href="{% url 'items' %}">All Items</a></li>
					<li><a href="{% url 'owners' %}">All Owners</a></li>
					<br>
					{% if user.is_authenticated %}
					<li><b>User:</b> {{ user.get_username }}</li>
					<li><a href="{% url 'my-borrowed' %}">My Borrowed</a></li>
					<li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
					{% else %}
					<li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
					{%endif%}
				</ul>
				{% endblock %}
			</div>
			<div class = "col-sm-10">
				{% block content %}{% endblock %}
			</div>
		</div>
	</div>
</body>
</html>

catalog/templates/catalog/item_detail.html
{% extends "base_generic.html" %}
{% block content %}
	<h1>{{ item.name }}</h1>
	<p><strong>Owner:</strong> <a href="">{{ item.owner }}</a></p>
	<p><strong>Description:</strong> {{ item.summary }}</p>
	<p><strong>Category:</strong> {% for category in item.category.all %} {{ category }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

	<div style="margin-left:20px;margin-top:20px">
		<h4>Available Stock</h4>
		{% for copy in item.iteminstance_set.all %}
		<hr>
		<p class="{% if copy.status == 'a' %} text-success {% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
		{% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
		<p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
		{% endfor %}
	</div>
{% endblock %}

catalog/templates/catalog/item_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Item List</h1>

	{% if item_list %}
	<ul>
		{% for item in item_list %}
		<li>
			<a href="{{item.get_absolute_url}}"> {{item.name}} </a> ({{item.owner}})
		</li>
		{% endfor %}
	</ul>
	{% else %}
		<p>There are no available items.</p>
	{% endif %}
	
{% endblock %}

catalog/templates/catalog/iteminstance_list_borrowed.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Your Borrowed Items</h1>

{% if iteminstance_list %}
<ul>
	{% for x in iteminstance_list %}
	<li class = "{% if x.is_overdue %}text-danger{% endif %}">
		<a href="{% url 'item-detail' x.item.pk %}">{{x.item.name}} </a> ({{ x.due_back }})
	</li>
	{%endfor%}
</ul>

{% else %}
<p>You have not borrowed anything.</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/owner_detail.html
{% extends "base_generic.html" %}
{% block content %}
	<h1>{{ owner.first_name }} {{ owner.last_name }}</h1>
	<p><strong>Date of Birth: </strong> {{ owner.date_of_birth }} </p>
	<p><strong>Location: </strong> {{ owner.location }}</p>

	<div style="margin-left:20px;margin-top:20px">
		<h4>Current Items</h4>
		<dl>
			{% for item in owner.item_set.all %}
			<dt><a href="{% url 'item-detail' item.pk %}">{{item}}</a> ({{item.iteminstance_set.all.count}})</dt>
			<dd>{{item.summary}}</dd>
			{% endfor %}
		</dl>
	</div>
{% endblock %}

catalog/templates/catalog/owner_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Owner List</h1>

	{% if owner_list %}
	<ul>
		{% for owner in owner_list %}
		<li>
			<a href="{{owner.get_absolute_url}}"> {{owner.first_name}} {{owner.last_name}} </a>
		</li>
		{% endfor %}
	</ul>
	{% else %}
		<p>There are no current owners.</p>
	{% endif %}
	
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Borrow Bro Home</h1>
<p>Welcome to <em>Borrow Bro</em>! Here, you can borrow anything under the sun.</p>

<h2>Content</h2>
<p>Currently, we have the following record count:</p>
<ul>
	<li><strong>Items:</strong> {{num_items}}</li>
	<li><strong>Copies:</strong> {{num_instances}}</li>
	<li><strong>Items Available:</strong> {{num_instances_available}}</li>
	<li><strong>Owners:</strong> {{num_owners}}</li>
</ul>

<p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>

{% endblock %}